### ISSUE TITLE
Issue with color

### ISSUE THREAD

**Issue by chervaliery** [no0be/DNSlivery#2]
After error, the color is kept in the shell:

![image](https://user-images.githubusercontent.com/10849551/51971842-6cb63000-247a-11e9-9007-0a39206de0c9.png)

![image](https://user-images.githubusercontent.com/10849551/51971728-24970d80-247a-11e9-9013-e07e633dab09.png)

**Comment by no0be** [comment]
Thank you for pointing that out.

Fixed in commit [`32dffbd1d5e74bb6b09b4ef889c021031d9973ea`](https://github.com/no0be/DNSlivery/commit/32dffbd1d5e74bb6b09b4ef889c021031d9973ea).
